travis:
  secure:
    BINSTAR_TOKEN: TQD9siwvwlOxyO+n6TjEk+WaHN2xIROguuPSl/E3WgZytbR+mRTPVSjh6R95zJYhW0nwRRkQtUXHOBNcJMF/cN4zQje8TAD61d6nLQcrCspS9EnMnebfqaQz6tJnWPkE+lx/7UYL99TAXkjlIcMgfzusNEXA201mQ6KnRtl3ZE6jcQ7R8TIo484tBTOKZvO02BJLtLn7JeN2mMKGOA/IoD1M+op/Iqlw+FWy8s5DOvRKaZ7Fkxu+BHDYwBSAe2l24FzFW1gX20LdQSGKYH/qqfV+EcEE31CqBJr6J9+LXy+ewY9FcD6/EihA1dodQYpFgabwQ8aFde+wE37rE6DcMO8Prd+BrcHiw27SZr3PoY8NmAeweiBxHydSBB0z50yU5pDiXBLlaM7n53l40rDLcEON7LlR5QeK47GjD8eUfmbz0vbZSI5K5vfwa8yC4ZsajSSnchk/zVdKrKNGR4tfMuNsRqVNkfTZTQKNy+vglfYlqweXuMwpjyCsO17bCzgv+lf/0WPwL42GMlW4lz+Ge++pdX3dHhE7XrZTP0CxWXM61lJkXrJFkhEhtZ2AMlGW8or+VAkCc7pajzxnOi58qVtNqFPO2ID+uvK94EnPTVHY2dp7r6AW6M8QAhPsWqBk3+uIPoEnYg/D3Ss8r1Jv9IFDgS5u5ayuMb70Yi3mATc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
